#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum Feature {
    MVP,
    Atomics,
    MutableGlobals,
    TruncSat,
    SIMD,
    BulkMemory,
    SignExt,
    ExceptionHandling,
    TailCall,
    ReferenceTypes,
    Multivalue,
    GC,
    Memory64,
    TypedFunctionReferences,
    GCNNLocals,
    RelaxedSIMD,
    ExtendedConst,
    All,
    AllPossible,
}
