#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum Feature {
    Mvp,
    Atomics,
    MutableGlobals,
    TruncSat,
    Simd,
    BulkMemory,
    SignExt,
    ExceptionHandling,
    TailCall,
    ReferenceTypes,
    Multivalue,
    Gc,
    Memory64,
    TypedFunctionReferences,
    GcNnLocals,
    RelaxedSimd,
    ExtendedConst,
    All,
    AllPossible,
}
