name: CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master", "ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        rust: [nightly, beta, stable, 1.48.0]
        include:
          - name: gcc-7
            os: ubuntu-20.04
            compiler: gcc-7
          - name: clang-3.9
            os: ubuntu-20.04
            compiler: clang-3.9

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Checkout submodule
          run: git submodule update --init --recursive
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo fmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --workspace --tests -- -Dclippy::all